
export const columns = [
    {
        "title": 'First Name ',
        "dataIndex": 'firstName',
        "key": 'firstName',
        sorter: (a, b) => a.firstName.localeCompare(b.firstName),
        defaultSortOrder: 'descend',
        ellipsis: true,
    },
    {
        "title": 'Last Name',
        "dataIndex": 'lastName',
        "key": 'lastName',
        sorter: (a, b) => a.lastName.localeCompare(b.lastName),
        defaultSortOrder: 'descend',
        ellipsis: true,
    },
    {
        "title": 'Start date',
        "dataIndex": 'startDate',
        "key": 'startDate',
        defaultSortOrder: 'descend',
        sorter: (a, b) => a.startDate - b.startDate,
        ellipsis: true,
    },
    {
        "title": 'Department',
        "dataIndex": 'department',
        "key": 'department',
        sorter: (a, b) => a.department.localeCompare(b.department),
        defaultSortOrder: 'descend',
        ellipsis: true,
    },
    {
        "title": 'Birthdate',
        "dataIndex": 'birthdate',
        "key": 'birthdate',
        defaultSortOrder: 'descend',
        sorter: (a, b) => a.birthdate - b.birthdate,
        ellipsis: true,
    },
    {
        "title": 'Street',
        "dataIndex": 'street',
        "key": 'street',
        sorter: (a, b) => a.street.localeCompare(b.street),
        defaultSortOrder: 'descend',
        ellipsis: true,
    },
    {
        "title": 'City',
        "dataIndex": 'city',
        "key": 'city',
        sorter: (a, b) => a.city.localeCompare(b.city),
        defaultSortOrder: 'descend',
        ellipsis: true,
    },
    {
        "title": 'State',
        "dataIndex": 'state',
        "key": 'state',
        sorter: (a, b) => a.state.localeCompare(b.state),
        defaultSortOrder: 'descend',
        ellipsis: true,
    },
    {
        "title": 'Zip Code',
        "dataIndex": 'zipcode',
        "key": 'zipcode',
        defaultSortOrder: 'descend',
        sorter: (a, b) => a.zipcode - b.zipcode,
        ellipsis: true,
    },
    // {
    //     "title": 'Action',
    //     "dataIndex": '',
    //     "key": 'X',
    //     width: '4rem',
    //     align:'center',
    //     render: () => <a>X</a>,
    // },
];